[theme]
primaryColor = "#c39bff"
backgroundColor = "#0e0e0e"
secondaryBackgroundColor = "#1a1919"
textColor = "#ffffff"
font = "sans serif"

[server]
headless = true
port = 8501

[browser]
gatherUsageStats = false
